CRITICAL:root:The piecewise candidate function was synthesized in time_synthesis0.3238708972930908time_synthesis seconds
Traceback (most recent call last):
  File "/home/lbattista/piecewise_lyap/semialgebraic_invariants/barrier/utils.py", line 85, in get_mathsat_smtlib
    solver = env.factory.Solver(name=name, logic=logics[0])
  File "/home/lbattista/.local/lib/python3.8/site-packages/pysmt/factory.py", line 437, in Solver
    return self.get_solver(name=name,
  File "/home/lbattista/.local/lib/python3.8/site-packages/pysmt/factory.py", line 91, in get_solver
    self._get_solver_class(solver_list=self._all_solvers,
  File "/home/lbattista/.local/lib/python3.8/site-packages/pysmt/factory.py", line 151, in _get_solver_class
    raise NoSolverAvailableError("%s '%s' is not available" % \
pysmt.exceptions.NoSolverAvailableError: Solver 'mathsat-smtlib' is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lbattista/piecewise_lyap/semialgebraic_invariants/piecewise_lyap_expeval.py", line 307, in <module>
    main(args)
  File "/home/lbattista/piecewise_lyap/semialgebraic_invariants/piecewise_lyap_expeval.py", line 287, in main
    certified = certify_piecewise_lyap(dyn_systems, switching_predicate_mode0_less0, Candidate_lyap, solver = new_solver_f())
  File "/home/lbattista/piecewise_lyap/semialgebraic_invariants/barrier/utils.py", line 87, in get_mathsat_smtlib
    raise SolverAPINotFound
pysmt.exceptions.SolverAPINotFound
